# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0.0.post22+g9ff1841.d20260226'
__version_tuple__ = version_tuple = (1, 0, 0, 'g9ff1841.d20260226')
